# Generated by Django 5.0.6 on 2024-07-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogusers',
            managers=[
            ],
        ),
    ]
