# Generated by Django 5.0.6 on 2024-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogusers_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogusers',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogusers',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogusers',
            name='profession',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
